### ISSUE TITLE
Mark commands (and flags) as hidden

### ISSUE THREAD

**Issue by sethvargo** [mitchellh/cli#65]
There isn't currently a way to mark a subcommand as "hidden". It's possible to filter help output to exclude it using a `HelpFunc`, but the subcommand still appears in the autocompletion. There should either be a way to customize the list of commands which are auto-completed or (better), a first-class mechanism for marking a command as hidden.

There are a few use cases here, the most prominent being backwards compatibility. I may want to introduce a new command to do something, but I want to have the old command around with a warning for a few releases. 

Another use case involves hidden "internal-only" commands. Sometimes you want some flags or commands that are for internal use only. Again, there's currently no way to achieve this nicely.

/cc @dadgar

**Comment by mitchellh** [comment]
![Yes](http://gifimage.net/wp-content/uploads/2017/08/yes-gif-12.gif)

I'll get started on this soon.

**Comment by dadgar** [comment]
@mitchellh What are you thinking of doing? Another filter function? It may be nice to just have simple structs that define commands/flags that can be passed in and these have options on them. Would make it possible to add interfaces on them so that help could be auto-generated etc. Having flag sets attached to the command would be nice. Auto-complete will need to parse flags as well so everyone will need to hack together separate solutions at this point.

I believe @sethvargo has some nice flags structs in a Vault PR.

**Comment by mitchellh** [comment]
I'm not planning on touching flags at all, this is just a command-level thing to hide from the help map and the autocomplete map.

**Comment by dadgar** [comment]
@mitchellh Understood. Was just suggesting it may be worth taking another look at this now that all the tools are building slightly separate solutions arounds help output/flags/autocomplete/etc

**Comment by mitchellh** [comment]
I don't think this will affect that, since hidden/not hidden will always be a parent feature you'd want over fine tuning help output. I think flags should be taken a look at as soon as we look at help more seriously since those are tied together.
